@extends('template.master')
@section('title','Buku - PerpusKita')
@section('content')
<div class="page-header"><div class="d-flex justify-content-between align-items-center"><div><h2 class="fw-bold mb-1"><i class="bi bi-book me-2"></i>Data Buku</h2><p class="mb-0 opacity-75">Kelola koleksi buku perpustakaan.</p></div><button class="btn btn-add" data-bs-toggle="collapse" data-bs-target="#formBuku"><i class="bi bi-plus-lg me-1"></i>Tambah Buku</button></div></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle me-2"></i>{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if(session('error'))<div class="alert alert-danger alert-dismissible fade show"><i class="bi bi-exclamation-circle me-2"></i>{{ session('error') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="collapse mb-4" id="formBuku"><div class="card custom-card shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Tambah Buku</h5><form action="{{ route('buku.store') }}" method="POST">@csrf<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Judul</label><input name="judul" class="form-control" required></div><div class="col-md-6 mb-3"><label class="form-label">Penulis</label><input name="penulis" class="form-control" required></div><div class="col-md-4 mb-3"><label class="form-label">Tahun Terbit</label><input type="number" name="tahun_terbit" class="form-control" min="1900" max="2100" required></div><div class="col-md-4 mb-3"><label class="form-label">Stok</label><input type="number" name="stok" class="form-control" min="0" required></div><div class="col-md-4 mb-3"><label class="form-label">Kategori</label><select name="kategori_id" class="form-select" required><option value="">-- Pilih Kategori --</option>@foreach($kategori as $k)<option value="{{ $k->id }}">{{ $k->nama }}</option>@endforeach</select></div></div><button class="btn btn-add"><i class="bi bi-save me-1"></i>Simpan Buku</button></form></div></div></div>
<div class="card custom-card shadow-sm"><div class="card-body p-0"><div class="p-4"><h5 class="fw-bold mb-1">Daftar Buku</h5><small class="text-muted">Data koleksi buku PerpusKita.</small></div><div class="table-responsive"><table class="table custom-table mb-0"><thead><tr><th>No</th><th>Judul</th><th>Penulis</th><th>Tahun</th><th>Stok</th><th>Kategori</th><th>Aksi</th></tr></thead><tbody>@forelse($buku as $item)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $item->judul }}</strong></td><td>{{ $item->penulis }}</td><td>{{ $item->tahun_terbit }}</td><td><span class="badge rounded-pill" style="background:#d9e2cf;color:#435334;">{{ $item->stok }}</span></td><td>{{ $item->kategori }}</td><td><div class="d-flex gap-1"><a href="{{ route('buku.show', $item->id) }}" class="btn btn-sm btn-info text-white" title="Lihat"><i class="bi bi-eye"></i></a><a href="{{ route('buku.edit', $item->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="bi bi-pencil"></i></a><form action="{{ route('buku.destroy', $item->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Yakin ingin menghapus data ini?');">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-danger" title="Hapus"><i class="bi bi-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada data buku.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
