@extends('template.master')
@section('title','Kategori - PerpusKita')
@section('content')
<div class="page-header"><div class="d-flex justify-content-between align-items-center"><div><h2 class="fw-bold mb-1"><i class="bi bi-tags me-2"></i>Kategori Buku</h2><p class="mb-0 opacity-75">Kelola kategori koleksi buku.</p></div><button class="btn btn-add" data-bs-toggle="collapse" data-bs-target="#formKategori"><i class="bi bi-plus-lg me-1"></i>Tambah Kategori</button></div></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle me-2"></i>{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if(session('error'))<div class="alert alert-danger alert-dismissible fade show"><i class="bi bi-exclamation-circle me-2"></i>{{ session('error') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="collapse mb-4" id="formKategori"><div class="card custom-card shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Tambah Kategori</h5><form action="{{ route('kategori.store') }}" method="POST">@csrf<div class="mb-3"><label class="form-label">Nama Kategori</label><input type="text" name="nama" class="form-control" required></div><button class="btn btn-add"><i class="bi bi-save me-1"></i>Simpan Kategori</button></form></div></div></div>
<div class="card custom-card shadow-sm"><div class="card-body p-0"><div class="p-4"><h5 class="fw-bold mb-1">Daftar Kategori</h5><small class="text-muted">Data kategori buku.</small></div><div class="table-responsive"><table class="table custom-table mb-0"><thead><tr><th>No</th><th>Nama Kategori</th><th>Aksi</th></tr></thead><tbody>@forelse($kategori as $item)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $item->nama }}</strong></td><td><div class="d-flex gap-1"><a href="{{ route('kategori.show', $item->id) }}" class="btn btn-sm btn-info text-white" title="Lihat"><i class="bi bi-eye"></i></a><a href="{{ route('kategori.edit', $item->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="bi bi-pencil"></i></a><form action="{{ route('kategori.destroy', $item->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Yakin ingin menghapus data ini?');">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-danger" title="Hapus"><i class="bi bi-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">Belum ada data kategori.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
