@extends('template.master')
@section('title','Pengembalian - PerpusKita')
@section('content')
<div class="page-header"><div class="d-flex justify-content-between align-items-center"><div><h2 class="fw-bold mb-1"><i class="bi bi-arrow-return-left me-2"></i>Pengembalian</h2><p class="mb-0 opacity-75">Kelola pengembalian buku dan denda.</p></div><button class="btn btn-add" data-bs-toggle="collapse" data-bs-target="#formPengembalian"><i class="bi bi-plus-lg me-1"></i>Proses Pengembalian</button></div></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle me-2"></i>{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if(session('error'))<div class="alert alert-danger alert-dismissible fade show"><i class="bi bi-exclamation-circle me-2"></i>{{ session('error') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="collapse mb-4" id="formPengembalian"><div class="card custom-card shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Proses Pengembalian</h5><form action="{{ route('pengembalian.store') }}" method="POST">@csrf<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Peminjaman</label><select name="peminjaman_id" class="form-select" required><option value="">-- Pilih Peminjaman --</option>@foreach($peminjaman as $p)<option value="{{ $p->id }}">{{ $p->anggota }} - {{ $p->buku }}</option>@endforeach</select></div><div class="col-md-3 mb-3"><label class="form-label">Tanggal Kembali</label><input type="date" name="tanggal_kembali" class="form-control" required></div><div class="col-md-3 mb-3"><label class="form-label">Denda</label><input type="number" name="denda" class="form-control" min="0" step="0.01" value="0" required></div></div><button class="btn btn-add"><i class="bi bi-check2-circle me-1"></i>Proses Pengembalian</button></form></div></div></div>
<div class="card custom-card shadow-sm"><div class="card-body p-0"><div class="p-4"><h5 class="fw-bold mb-1">Daftar Pengembalian</h5><small class="text-muted">Riwayat pengembalian buku.</small></div><div class="table-responsive"><table class="table custom-table mb-0"><thead><tr><th>No</th><th>Anggota</th><th>Buku</th><th>Tanggal Kembali</th><th>Denda</th><th>Aksi</th></tr></thead><tbody>@forelse($pengembalian as $item)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $item->anggota }}</strong></td><td>{{ $item->buku }}</td><td>{{ $item->tanggal_kembali }}</td><td>Rp {{ number_format($item->denda, 0, ',', '.') }}</td><td><div class="d-flex gap-1"><a href="{{ route('pengembalian.show', $item->id) }}" class="btn btn-sm btn-info text-white" title="Lihat"><i class="bi bi-eye"></i></a><a href="{{ route('pengembalian.edit', $item->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="bi bi-pencil"></i></a><form action="{{ route('pengembalian.destroy', $item->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Yakin ingin menghapus data ini?');">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-danger" title="Hapus"><i class="bi bi-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada data pengembalian.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
